"""schema inicial UniCare

Revision ID: 6962282d3bc9
Revises: 
Create Date: 2026-10-04 20:04:31.403311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6962282d3bc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tabela_afetada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('endereco_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_usuario_id'), 'logs_auditoria', ['usuario_id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cpf_rg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_nascimento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eh_menor', sa.Boolean(), nullable=False),
    sa.Column('nome_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prontuario_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf_rg'), 'pacientes', ['cpf_rg'], unique=True)
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('perfil', sa.Enum('ESTAGIARIO', 'SUPERVISOR', 'RECEPCAO', 'RT', name='perfilusuario'), nullable=False),
    sa.Column('curso', sa.Enum('PSICOLOGIA', 'ODONTOLOGIA', 'GERAL', name='cursousuario'), nullable=False),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registro_profissional', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_matricula'), 'usuarios', ['matricula'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('paciente_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estagiario_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estagiario_matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horario', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turno', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sala_ou_cadeira', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_consulta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'PRESENTE', 'EM_ATENDIMENTO', 'CONCLUIDO', 'FALTOU', 'CANCELADO', name='statusagendamento'), nullable=False),
    sa.Column('observacao_logistica', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_paciente_id'), 'agendamentos', ['paciente_id'], unique=False)
    op.create_table('fichas_odonto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('dupla_estagiarios', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dente_regiao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('procedimento_realizado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('materiais_utilizados', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('anestesico', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alerta_alergia', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parecer_supervisor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('EM_ELABORACAO', 'AGUARDANDO_VALIDACAO', 'VALIDADO', 'DEVOLVIDO_PARA_AJUSTE', name='statusprontuario'), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fichas_odonto_paciente_id'), 'fichas_odonto', ['paciente_id'], unique=False)
    op.create_table('prontuarios_psico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('paciente_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estagiario_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estagiario_matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supervisor_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_sessao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_sessao', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inicio_sessao_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meio_sessao_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fim_sessao_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parecer_supervisor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('EM_ELABORACAO', 'AGUARDANDO_VALIDACAO', 'VALIDADO', 'DEVOLVIDO_PARA_AJUSTE', name='statusprontuario'), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prontuarios_psico_paciente_id'), 'prontuarios_psico', ['paciente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prontuarios_psico_paciente_id'), table_name='prontuarios_psico')
    op.drop_table('prontuarios_psico')
    op.drop_index(op.f('ix_fichas_odonto_paciente_id'), table_name='fichas_odonto')
    op.drop_table('fichas_odonto')
    op.drop_index(op.f('ix_agendamentos_paciente_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_matricula'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf_rg'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_logs_auditoria_usuario_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    # ### end Alembic commands ###

    # O drop_table NAO remove os tipos ENUM nativos do PostgreSQL. Sem esta limpeza
    # explicita, um ciclo downgrade -> upgrade falha com "type ... already exists".
    # checkfirst=True mantem o downgrade idempotente.
    sa.Enum(name='statusprontuario').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='statusagendamento').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cursousuario').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='perfilusuario').drop(op.get_bind(), checkfirst=True)
