"""demandas de estagio (RF-009)

Revision ID: 779eeac7703e
Revises: 6699e657b519
Create Date: 2026-10-09 16:49:34.780190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '779eeac7703e'
down_revision: Union[str, Sequence[str], None] = '6699e657b519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demandas_estagio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_nome', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('aluno_matricula', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('curso', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('procedimento_desejado', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.Enum('ALTA', 'MEDIA', 'NORMAL', name='prioridadedemanda'), nullable=False),
    sa.Column('data_solicitacao', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'AGENDADO', name='statusdemanda'), nullable=False),
    sa.Column('criado_em', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandas_estagio_aluno_matricula'), 'demandas_estagio', ['aluno_matricula'], unique=False)
    op.create_index(op.f('ix_demandas_estagio_curso'), 'demandas_estagio', ['curso'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demandas_estagio_curso'), table_name='demandas_estagio')
    op.drop_index(op.f('ix_demandas_estagio_aluno_matricula'), table_name='demandas_estagio')
    op.drop_table('demandas_estagio')
    # ### end Alembic commands ###

    # op.drop_table NAO remove os tipos ENUM nativos do PostgreSQL. Sem esta limpeza
    # explicita, um ciclo downgrade -> upgrade falha com "type ... already exists".
    sa.Enum(name='statusdemanda').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='prioridadedemanda').drop(op.get_bind(), checkfirst=True)
